blank_issues_enabled: false
contact_links:
  - name: Organização ARQDSW
    url: https://github.com/pedrocampos0/sistema-atendimento-sspdf
    about: Sistema de Atendimento a Denúncias Anônimas - Secretaria de Segurança Pública do Distrito Federal.